-- FIRST RETURN THE BOOK SO FINE IS CREATED (IF NOT DONE ALREADY)
CALL return_book(1001);

-- PAY THE FINE
CALL pay_fine(1);

-- VERIFY
SELECT * FROM fine WHERE fine_id = 1;

-- TRY PAYING AGAIN - SHOULD FAIL
CALL pay_fine(1);